### ISSUE TITLE
Just to confirm this repository is for OIM3690 project, correct?

### ISSUE THREAD

**Issue by lzblack** [tomasgarcia3/oim3690-Term-Poroject#1]

**Comment by tomasgarcia3** [comment]
yes professor sorry for the misunderstanding!

**Comment by lzblack** [comment]
No worries. 😁

Repo name changed to '[oim3690-Term-Poroject](https://github.com/tomasgarcia3/oim3690-Term-Poroject)'.
Issue closed.
