### ISSUE TITLE
Linking photos

### ISSUE THREAD

**Issue by samantha32123** [tomasgarcia3/oim3690-Term-Poroject#4]
I got this comment from another classmate and thought is was a really cool idea; You could link the images on your home page so that they send you directly to that associated site page! (not necessary but would add another cool element).

**Comment by tomasgarcia3** [comment]
After reading this comment I decided to incorporate this feature into my website, so thank you for the help. I have added links to the images on my homepage so that it redirects them to the site for each topic.
