### ISSUE TITLE
Centering h1

### ISSUE THREAD

**Issue by samantha32123** [tomasgarcia3/oim3690-Term-Poroject#5]
The 'h1' heading on the contact page looks nicely centered, however when you navigate to the destination spots the heading seems to be placed slightly to the left. Might be worth aligning with the contact page header so it flows more seamlessly.

**Comment by tomasgarcia3** [comment]
Thanks for this feedback, I have centered the headers and even made some arrangements to make most of the pages compatible with mobile.
